esphome:
  name: atom-echo-1
  friendly_name: "Atom Echo 1"
  min_version: 2024.7.0

esp32:
  board: m5stack-atom
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "srKx6+0CD60/6SLLS/AevGdR3xGZIsQoGUWo5EvnRC8="

ota:
  platform: esphome
  password: "dex92dex"

wifi:
  ssid: "Korobok"
  password: "dex92dex"

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO19

microphone:
  - platform: i2s_audio
    id: echo_microphone
    adc_type: external
    i2s_din_pin: GPIO23
    pdm: true

speaker:
  - platform: i2s_audio
    id: echo_speaker
    dac_type: external
    i2s_dout_pin: GPIO22

micro_wake_word:
  models:
    - model: github://velorass/microwakeword_models/models/havrylo.json@main

  on_wake_word_detected:
    - light.turn_on:
        id: led
        red: 0%
        green: 100%
        blue: 0%
    - voice_assistant.start:

voice_assistant:
  microphone: echo_microphone
  speaker: echo_speaker
  on_start:
    - light.turn_on:
        id: led
        effect: "Listening"
  on_tts_end:
    - light.turn_off: led
  on_end:
    - light.turn_off: led
  on_error:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
    - delay: 2s
    - light.turn_off: led

light:
  - platform: esp32_rmt_led_strip
    id: led
    pin: GPIO27
    num_leds: 1
    chipset: SK6812
    rgb_order: GRB
    name: "Status LED"
    effects:
      - pulse:
          name: "Listening"
          min_brightness: 20%
          max_brightness: 100%

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: "Button"
    on_click:
      - voice_assistant.start:
